# vim:sw=2:et:

sudo: false
language: erlang
notifications:
  email:
    - alerts@rabbitmq.com
addons:
  apt:
    packages:
      - awscli
      - xsltproc
cache:
  apt: true
env:
  global:
    - secure: mgDm79Kn76fo4O9CiaFaFNrRnqXKm8cNHHdjAuD40VDbXIS3flTtLdcY2uV7HlB18M5ZIhiZvUC8XYgsdBt3tT66acNbYiBaJ0PaSz6APMqBZSoYmq1RCHlwpZGZbR6OdXEmVeLWAL82Qh7cAYo1a8IRro+ZObG7tp/sDITggkA=
    - secure: DdcLcK8M9lbc7ISuw3VlJFNVxckLr+B86Mhv8L3Q+dF6EP+god45ICHr6eEIpUnnBtCgO/qNETrnDhKO6PBA9gjsgRtdKwXfEZX32ZZUfmp5DHQAkpqbHYOULcOpKyfLlU9rojqcUiPzxUKxpolSCybJ6B0UcEjhGx9bYs/ssEk=

otp_release:
  - "R16B03-1"
  - "19.3"
  - "20.1"

before_script:
  # The checkout made by Travis is a "detached HEAD" and branches
  # information is missing. Our Erlang.mk's git_rmq fetch method relies
  # on it, so we need to restore it.
  #
  # We simply fetch master and, if it exists, stable branches. A branch
  # is created, pointing to the detached HEAD.
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream stable:stable || :
    git fetch upstream master:master || :

script:
  - make xref
  - make tests

after_failure:
  - |
    cd "$TRAVIS_BUILD_DIR"
    if test -d logs && test "$AWS_ACCESS_KEY_ID" && test "$AWS_SECRET_ACCESS_KEY"; then
      archive_name="$(basename "$TRAVIS_REPO_SLUG")-$TRAVIS_JOB_NUMBER"

      tar -c --transform "s/^logs/${archive_name}/" -f - logs | \
        xz > "${archive_name}.tar.xz"

      aws s3 cp "${archive_name}.tar.xz" s3://server-release-pipeline/travis-ci-logs/ \
        --region eu-west-1 \
        --acl public-read
    fi
